# Use official Python 3.12 slim image for a smaller footprint
FROM python:3.12-slim
# Set working directory
WORKDIR /app
# Copy requirements file
COPY app/private/requirements.txt .
# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

COPY app/private/.env-dev /app/.env

# Copy application code
COPY app/private/src/ .

# Command to run the application
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8010", "--reload"]