services:
  traefik:
    image: traefik:latest
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
    restart: always
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.localhost`)
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.entrypoints=web

  tickermind-web:
    build: 
      context: .
      dockerfile: Dockerfile.web.dev
    container_name: tickermind-web
    user: root
    environment:
      - VITE_HOST=0.0.0.0
      - DOMAIN=${DOMAIN:-tickermind.localhost}
    restart: unless-stopped
    volumes:
    - ./app/public/src:/app/src
    labels:
      - traefik.enable=true
      - traefik.http.routers.tickermind-web.rule=Host(`tickermind.localhost`)
      - traefik.http.routers.tickermind-web.entrypoints=web
      - traefik.http.services.tickermind-web.loadbalancer.server.port=3000

  tickermind-api:
    build: 
      context: .
      dockerfile: Dockerfile.api.dev
    container_name: tickermind-api
    user: root
    volumes:
      - ./app/private/data/:/data
      - ./app/private/src:/app # enables live edits and reload.
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.tickermindapi.rule=Host(`api2.localhost`)
      - traefik.http.routers.tickermindapi.entrypoints=web
      - traefik.http.services.tickermindapi.loadbalancer.server.port=8010
      - traefik.http.middlewares.cors.headers.accessControlAllowMethods=GET,POST,OPTIONS
      - traefik.http.middlewares.cors.headers.accessControlAllowOriginList=http://tickermind.localhost,http://localhost:3000
      - traefik.http.middlewares.cors.headers.accessControlAllowHeaders=Content-Type
      - traefik.http.middlewares.cors.headers.accessControlMaxAge=100
      - traefik.http.middlewares.cors.headers.addVaryHeader=true
      - traefik.http.routers.tickermindapi.middlewares=cors
    
  adminer:
    image: adminer:latest
    container_name: tickermind-adminer
    restart: unless-stopped
    user: root
    labels:
      - traefik.enable=true
      - traefik.http.routers.adminer.rule=Host(`adminer.localhost`)
      - traefik.http.routers.adminer.entrypoints=web
      - traefik.http.services.adminer.loadbalancer.server.port=8080
    volumes:
      - ./app/private/adminer/plugins/login-password-less.php:/var/www/html/plugins-enabled/login-password-less.php
      - ./app/private/data/:/data
    environment:
      - ADMINER_DEFAULT_SERVER=
      - ADMINER_DESIGN=pepa-linha
      # Sqlite, username:BLANK, password: admin, database: /data/stocks.db