# Use official Python 3.12 slim image for a smaller footprint
FROM python:3.12-slim

# Set working directory
WORKDIR /app

RUN pip install --upgrade pip
RUN pip install torch==2.8.0 --index-url https://download.pytorch.org/whl/cu128 
COPY app/private/requirements.txt app/private/.env-dev app/private/src/ /app/
RUN pip install -r requirements.txt
ENV PYTHONPATH=/app
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8010", "--reload"]